// <auto-generated />
using System;
using IPOClient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPOClient.Migrations
{
    [DbContext(typeof(IPOClientDbContext))]
    [Migration("20260123095352_AddRemarkOrderTable")]
    partial class AddRemarkOrderTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_ApiLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Method")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("RequestTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestTime");

                    b.HasIndex("StatusCode");

                    b.ToTable("IPO_ApiLogs");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_BuyerOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<bool>("ApplicateRate")
                        .HasColumnType("bit");

                    b.Property<int>("BuyerMasterId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvestorType")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderCategory")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<string>("PremiumStrikePrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RemarksIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("BuyerMasterId");

                    b.ToTable("IPO_BuyerOrder", (string)null);
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_BuyerPlaceOrderMaster", b =>
                {
                    b.Property<int>("BuyerMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuyerMasterId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("IPOId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BuyerMasterId");

                    b.HasIndex("GroupId");

                    b.ToTable("IPO_BuyerPlaceOrderMaster", (string)null);
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_ClientDeleteHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalClientsDeleted")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.ToTable("IPO_ClientDeleteHistory", (string)null);
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_ClientDeleteHistoryDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("ClientDPId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("HistoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PANNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DetailId");

                    b.HasIndex("HistoryId");

                    b.ToTable("IPO_ClientDeleteHistoryDetail", (string)null);
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_ClientSetup", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("ClientDPId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PANNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ClientId");

                    b.HasIndex("GroupId");

                    b.ToTable("IPO_ClientSetup", (string)null);
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_GroupMaster", b =>
                {
                    b.Property<int>("IPOGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IPOGroupId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IPOId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IPOGroupId");

                    b.HasIndex("IPOId");

                    b.ToTable("IPO_GroupMaster", (string)null);
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_IPOMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BHNI_Percentage")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPOName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IPOType")
                        .HasColumnType("int");

                    b.Property<decimal?>("IPO_BHNI_Lot_Size")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("IPO_Retail_Lot_Size")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("IPO_SHNI_Lot_Size")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("IPO_Upper_Price_Band")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OpenIPOPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Retail_Percentage")
                        .HasColumnType("int");

                    b.Property<int?>("SHNI_Percentage")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_IPO_Size_Cr")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.HasIndex("IPOType");

                    b.ToTable("IPO_IPOMaster");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_Order_Remark", b =>
                {
                    b.Property<int>("RemarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemarkId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IPOId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RemarkId");

                    b.ToTable("IPO_OrderRemark");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_PlaceOrderChild", b =>
                {
                    b.Property<int>("POChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("POChildId"));

                    b.Property<int?>("AllotedQty")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChildOrderCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DematNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PANNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("POChildId");

                    b.HasIndex("OrderId");

                    b.ToTable("IPO_PlaceOrderChild", (string)null);
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_TypeMaster", b =>
                {
                    b.Property<int>("IPOTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IPOTypeID"));

                    b.Property<string>("IPOTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IPOTypeID");

                    b.ToTable("IPO_TypeMaster");

                    b.HasData(
                        new
                        {
                            IPOTypeID = 1,
                            IPOTypeName = "Main Board IPOs"
                        },
                        new
                        {
                            IPOTypeID = 2,
                            IPOTypeName = "SME IPOs"
                        });
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_UserMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("IPO_UserMasters");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_BuyerOrder", b =>
                {
                    b.HasOne("IPOClient.Models.Entities.IPO_BuyerPlaceOrderMaster", "BuyerMaster")
                        .WithMany("Orders")
                        .HasForeignKey("BuyerMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyerMaster");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_BuyerPlaceOrderMaster", b =>
                {
                    b.HasOne("IPOClient.Models.Entities.IPO_GroupMaster", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_ClientDeleteHistoryDetail", b =>
                {
                    b.HasOne("IPOClient.Models.Entities.IPO_ClientDeleteHistory", "History")
                        .WithMany("Details")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("History");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_ClientSetup", b =>
                {
                    b.HasOne("IPOClient.Models.Entities.IPO_GroupMaster", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_GroupMaster", b =>
                {
                    b.HasOne("IPOClient.Models.Entities.IPO_IPOMaster", "IPOMaster")
                        .WithMany()
                        .HasForeignKey("IPOId");

                    b.Navigation("IPOMaster");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_IPOMaster", b =>
                {
                    b.HasOne("IPOClient.Models.Entities.IPO_TypeMaster", "IPOTypeMaster")
                        .WithMany()
                        .HasForeignKey("IPOType");

                    b.Navigation("IPOTypeMaster");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_PlaceOrderChild", b =>
                {
                    b.HasOne("IPOClient.Models.Entities.IPO_BuyerOrder", "IPOOrder")
                        .WithMany("OrderChild")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IPOOrder");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_BuyerOrder", b =>
                {
                    b.Navigation("OrderChild");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_BuyerPlaceOrderMaster", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("IPOClient.Models.Entities.IPO_ClientDeleteHistory", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
